# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q230kF_jMj606rvGBPerUBXmeQnvzY_L
"""

import pandas as pd
import re

def limpiar_texto(texto):
    if not isinstance(texto, str):
        return ""
    texto = texto.lower()
    texto = re.sub(r'http\S+|www\S+|https\S+', '', texto, flags=re.MULTILINE)
    texto = re.sub(r'[^a-záéíóúñü\s0-9]', '', texto)
    texto = re.sub(r'\s+', ' ', texto).strip()
    return texto

def preprocesar_dataset(input_file, output_file):
    print(f"Procesando {input_file}...")
    df = pd.read_csv(input_file)
    columnas_basura = [col for col in df.columns if 'Unnamed' in col]
    df = df.drop(columns=columnas_basura)
    df = df.dropna(subset=['content'])
    df['score'] = pd.to_numeric(df['score'], errors='coerce')
    df = df.dropna(subset=['score'])

    def clasificar_sentimiento(score):
        if score <= 2: return 'Negativo'
        elif score == 3: return 'Neutro'
        else: return 'Positivo'

    df['sentimiento'] = df['score'].apply(clasificar_sentimiento)
    df['content_limpio'] = df['content'].apply(limpiar_texto)
    df = df[df['content_limpio'] != '']
    df.to_csv(output_file, index=False)

    print("Distribución de clases:")
    print(df['sentimiento'].value_counts())
    print("-" * 30)

# Ejecutamos la función para ambos archivos
preprocesar_dataset('Hinge.csv', 'Hinge_preprocesado.csv')
preprocesar_dataset('Boo.csv', 'Boo_preprocesado.csv')
print("¡Limpieza terminada con éxito!")